services:
  postgres:
    image: postgres:16-alpine
    container_name: futebol-postgres
    environment:
      POSTGRES_DB: futebol_dw
      POSTGRES_USER: futebol
      POSTGRES_PASSWORD: futebol
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futebol -d futebol_dw"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
